---
###########
#
# Overview: Configures SSH passwordless login
# Applies to: GSMO environments: DEV-INT, QA, Leagcy-QA
# Description: 
#   This ansible playbook will copy the SSH key pair of the source 
#   machine and place it on the destination machine
# 
# Prerequisites:
#   - Linux OS
#
# Author:
#   Mike Ellis 2/15/2019 (Leidos)
###########

- hosts: gsmodevint, gsmoqa
  remote_user: srvc-gsmo
  become: yes
  become_user: srvc-gsmo

  vars:
    users:
      - username: srvc-gsmo

  tasks:

  - name: ansible create .ssh directory 
    file:
      path: /home/srvc-gsmo/.ssh
      state: directory
      mode: 0700
      owner: srvc-gsmo
      group: games

  - name: Ansible create authorized_keys file if it doesn't exist
    file:
      path: "/home/srvc-gsmo/.ssh/authorized_keys"
      state: touch
      owner: srvc-gsmo
      group: games

  - name: copy pub key for srvc-gsmo to authorized_keys
    copy:
      src: "/home/{{ item.username }}/.ssh/id_rsa.pub"
      dest: "/home/{{ item.username }}/.ssh/authorized_keys"
      owner: "{{ item.username }}"
      group: games
      mode: "0644"
    with_items: "{{ users }}"

  - name: Update permissions on the file
    command: chmod 600 /home/srvc-gsmo/.ssh/authorized_keys

