---
###########
#
# Overview: Automate ssh key rotation
# Applies to: GSMO environments: DEV-INT, QA, Leagcy-QA
# Description: 
#   This ansible playbook will generate a new ssh key and copy
#   it to all thr targets in the inventory.  It will remove all the
#   old keys.
# 
# Prerequisites:
#   - Linux OS
#
# Example Command: ansible-playbook ansible/ssh-key-rotation.yml -i ansible/inventory.ini
#
# Author:
#   Mike Ellis 2/18/2019 (Leidos)
###########

- hosts: gsmodevint, gsmoqa
  remote_user: srvc-gsmo
  become: yes
  become_user: srvc-gsmo

  vars:
    ssh-key-bits: 4096
    passphrase: 38g!8bfu5M5yy84x
    ssh_key_comment: domain.example.com
    ssh_key_path: '{{ inventory_dir }}/new-ssh-key'
    is_exclusive: yes
    ssh_host_user: srvc-gsmo
    
    users:
      - username: srvc-gsmo

  tasks:

  - name: Generate a new ssh Key
    command: ssh-keygen
       -t ras
       -b {{ ssh_key_bits }}
       -N "{{ passphrase }}" -q
       -f {{ ssh_key_path }}
       -C {{ ssh_key_comment }}
    args:
      creates: '{{ ssh_key_path }}'
    delegate_to: localhost

  - name: Store then value of the public ssh key
      set_fact:
         ssh_connection_key: "{{ lookup('file', sshy_key_path + '.pub') }}"

  - name: Set Authorized key(s) to the authorized keys file
      become: yes
      become_user: root
      authorized_key:
        exclusive: '{{ is_exclusive }}'
      user: '{{ ssh_host_user }}'
      state: present
      key: "{{ ssh_connection_key }}"


  
