# Example that prints the loopback address and gateway for each host
- hosts: localhost
  tasks:

  - name: Host Information
    debug: msg="Hostname,IP,Time are {{ ansible_nodename }} and {{ ansible_default_ipv4.address }} and {{ ansible_date_time.iso8601 }}"

